name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'prisma/**'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'prisma/**'
      - '.github/workflows/backend-ci-cd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 20010511
          POSTGRES_DB: FormBuild_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: postgresql://postgres:20010511@localhost:5432/FormBuild_test
      
    - name: Run database migrations
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: postgresql://postgres:20010511@localhost:5432/FormBuild_test
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: postgresql://postgres:20010511@localhost:5432/FormBuild_test
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Build Docker image
      run: docker build -t form-builder-backend -f Dockerfile.backend .
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      run: |
        docker tag form-builder-backend ${{ secrets.DOCKERHUB_USERNAME }}/form-builder-backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/form-builder-backend:latest 