name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'prisma/**'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'prisma/**'
      - '.github/workflows/backend-ci-cd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 20010511
          POSTGRES_DB: FormBuild_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Create backend directory if it doesn't exist
      run: mkdir -p backend
        
    - name: Install dependencies
      run: |
        if [ -f "backend/package.json" ]; then
          cd backend && npm ci
        else
          echo "No package.json found in backend directory. Skipping dependency installation."
        fi
      
    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: postgresql://postgres:20010511@localhost:5432/FormBuild_test
      
    - name: Run database migrations
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: postgresql://postgres:20010511@localhost:5432/FormBuild_test
      
    - name: Run linting
      run: |
        if [ -f "backend/package.json" ]; then
          cd backend && npm run lint
        else
          echo "No package.json found in backend directory. Skipping linting."
        fi
      
    - name: Run tests
      run: |
        if [ -f "backend/package.json" ]; then
          cd backend && npm test
        else
          echo "No package.json found in backend directory. Skipping tests."
        fi
      env:
        DATABASE_URL: postgresql://postgres:20010511@localhost:5432/FormBuild_test
      
    - name: Build TypeScript
      run: |
        if [ -f "backend/package.json" ]; then
          cd backend && npm run build
        else
          echo "No package.json found in backend directory. Skipping build."
        fi
      
    - name: Build Docker image
      run: |
        if [ -f "backend/Dockerfile.backend" ]; then
          docker build -t form-builder-backend -f backend/Dockerfile.backend backend
        else
          echo "No Dockerfile.backend found in backend directory. Skipping Docker build."
        fi
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      run: |
        if [ -f "backend/Dockerfile.backend" ]; then
          docker tag form-builder-backend ${{ secrets.DOCKERHUB_USERNAME }}/form-builder-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/form-builder-backend:latest
        else
          echo "No Dockerfile.backend found in backend directory. Skipping Docker push."
        fi 