name: Deploy to EC2

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1 # Change this to your AWS region
  EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get GitHub Actions IP ranges
      run: |
        curl -s https://api.github.com/meta | jq -r '.actions[]' > github-actions-ips.txt
        echo "GitHub Actions IP ranges:"
        cat github-actions-ips.txt

    - name: Update EC2 Security Group
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr $(cat github-actions-ips.txt)

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Store SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        cat >>~/.ssh/config <<END
        Host ec2
          HostName ${{ env.EC2_HOST }}
          User ${{ env.EC2_USERNAME }}
          IdentityFile ~/.ssh/private.key
          StrictHostKeyChecking no
          ConnectTimeout 30
          ServerAliveInterval 60
        END

    - name: Create production env file
      run: |
        cat > .env.production << EOL
        DATABASE_URL=postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/FormBuild
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
        NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
        NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
        NODE_ENV=production
        NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
        EOL

    - name: Test SSH Connection
      run: |
        ssh -v -i ~/.ssh/private.key ec2 'echo "SSH connection successful"'
        if [ $? -ne 0 ]; then
          echo "SSH connection failed. Checking EC2 instance status..."
          aws ec2 describe-instance-status --instance-ids ${{ env.EC2_INSTANCE_ID }}
          exit 1
        fi

    - name: Deploy to EC2
      run: |
        # Create app directory and install Docker on EC2
        ssh -i ~/.ssh/private.key ec2 '
          # Create app directory if it doesn't exist
          mkdir -p ~/app
          
          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi
          
          # Install Docker Compose if not installed
          if ! command -v docker-compose &> /dev/null; then
            sudo apt-get install -y docker-compose
          fi
        '

        # Copy files to EC2
        scp -i ~/.ssh/private.key -r ./* ec2:~/app/
        
        # SSH into EC2 and run deployment commands
        ssh -i ~/.ssh/private.key ec2 '
          cd ~/app
          # Backup existing .env file if it exists
          if [ -f .env ]; then
            mv .env .env.backup
          fi
          # Copy production env file
          cp .env.production .env
          # Ensure proper permissions
          chmod 600 .env
          # Deploy with Docker
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
        ' 